services:
  collabora:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        nobrand: "yes" # Keep this if you want the CODE version
    image: smartdocs
    container_name: smartdocs
    restart: always
    network_mode: host
    # ports: # Not needed with network_mode: host
    #   - "127.0.0.1:9980:9980"
    cap_add:
      - MKNOD
      - SYS_ADMIN
    #privileged: true  # <-- ADDED BACK based on comments
    volumes:
      # Add read-only mounts for host timezone info
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment: 
      - extra_params=--o:mount_jail_tree=false --o:seccomp_action=allow --o:ssl.enable=false --o:user_interface.mode=classic
      - domain=(localhost|127\.0\.0\.1)
      - username=smartdocs
      - password="smartdocs2025" # Consider changing this password
      - aliasgroup1=http://localhost:8000